### ISSUE TITLE
AttributeError in Windows 10 + dev branch fresh install

### ISSUE THREAD

**Issue by DePierre** [CANToolz/CANToolz#20]
Sebastian tried to install CANToolz's dev branch on Windows 10 and got the following error:
```pytb
D:\CANToolz\bin>python cantoolz -g w -c D:\CANToolz\examples\can_sniff.py


   _____          _   _ _______          _
  / ____|   /\   | \ | |__   __|        | |
 | |       /  \  |  \| |  | | ___   ___ | |____
 | |      / /\ \ | . ` |  | |/ _ \ / _ \| |_  /
 | |____ / ____ \| |\  |  | | (_) | (_) | |/ /
  \_____/_/    \_\_| \_|  |_|\___/ \___/|_/___|



Traceback (most recent call last):
  File "cantoolz", line 103, in <module>
    main()
  File "cantoolz", line 82, in main
    can_engine.load_config(args.config)
  File "C:\Users\sebas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cantoolz-3.6.1-py3.6.egg\cantoolz\engine.py", line 267, in load_config
    self._init_module(path, module, init_params)
  File "C:\Users\sebas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cantoolz-3.6.1-py3.6.egg\cantoolz\engine.py", line 325, in _init_module
    self._modules[mod] = getattr(loaded_module, mod_name)(params)
AttributeError: module 'io/hw_USBtin' has no attribute 'io/hw_USBtin'

D:\CANToolz\bin>
```

**Comment by DePierre** [comment]
Installation logs look clean: https://pastebin.com/T2jDjw3k

Two possibilities about that bug:
+ `setuptools` does not properly copy the modules during installation (could be our `setup.py` file that is wrong
+ CANToolz' function to locate modules is not working on Windows

**Comment by DePierre** [comment]
The problem comes from the forward slashes in the example configuration files:
https://github.com/CANToolz/CANToolz/blob/6b4e9d4d3a410f12683dc11bc470e423bda7b3f7/examples/can_sniff.py#L2

The simplest but ugliest fix IMO would be to check for both '/' and '\' in the engine.py:
https://github.com/CANToolz/CANToolz/blob/6b4e9d4d3a410f12683dc11bc470e423bda7b3f7/cantoolz/engine.py#L216

Need to find a more elegant solution.
