### ISSUE TITLE
[cantoolz@3.7.0] [Failed with built-in test cases] Some self-test cases fail (1F/28).

### ISSUE THREAD

**Issue by Tom-python0121** [CANToolz/CANToolz#31]
Hello,I meet a problm about some self-test cases fail in cantoolz@3.7.0.
### Steps to reproduce the issue

```console
[root@centos8 spack-src]# ls
bin  build  cantoolz  CANToolz.egg-info  cantoolz.py  CONTRIBUTORS.md  examples  LICENSE.md  MANIFEST.in  NOTICE.md  README.md  setup.py  tests  VERSION.md
[root@centos8spack-src]#python setup.py test
……
ERROR: test_replay_uds_padding (tests.modules.test_replay.TestReplay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/tests/modules/test_replay.py", line 153, in test_replay_uds_padding
    self.CANEngine.load_config('tests/configurations/conf_replay_uds_padding.py')
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/engine.py", line 270, in load_config
    self._init_module(path, module, init_params)
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/engine.py", line 333, in _init_module
    self._modules[mod] = getattr(loaded_module, mod_name)(params)
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/module.py", line 62, in __init__
    self.do_init(params)
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/modules/io/hw_USBtin.py", line 206, in do_init
    self.last = time.clock()
AttributeError: module 'time' has no attribute 'clock'

======================================================================
ERROR: test_send_recieve (tests.modules.test_simple_io.TestSimpleIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/tests/modules/test_simple_io.py", line 9, in test_send_recieve
    self.CANEngine.load_config('tests/configurations/conf_simple_io.py')
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/engine.py", line 270, in load_config
    self._init_module(path, module, init_params)
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/engine.py", line 333, in _init_module
    self._modules[mod] = getattr(loaded_module, mod_name)(params)
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/module.py", line 62, in __init__
    self.do_init(params)
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/cantoolz/modules/io/hw_USBtin.py", line 206, in do_init
    self.last = time.clock()
AttributeError: module 'time' has no attribute 'clock'

======================================================================
FAIL: test_process (tests.stream.test_forced_sampler.TestForcedSampler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/root/spack-stage/spack-stage-py-cantoolz-3.7.0-jcmafxczouwkcgmi553yco57zygrmrpg/spack-src/tests/stream/test_forced_sampler.py", line 33, in test_process
    self.assertEqual(effects_count, 4)
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 28 tests in 0.060s

FAILED (failures=1, errors=26)
Test failed: <unittest.runner.TextTestResult run=28 errors=26 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=28 errors=26 failures=1>
```
**AttributeError: module 'time' has no attribute 'clock'** this question I have found the answer:**https://github.com/CANToolz/CANToolz/pull/30/commits/d75574523d3b273c40fb714532c4de27f9e6dd3e** ,However, it has been submitted and has not been merged and I am waiting.But **self.assertEqual(effects_count, 4)** should be be rewritten  as **self.assertEqual(effects_count, 3)** ，and the test can be passed.Do you think?

**Comment by DePierre** [comment]
@Tom-python0121 We just merged #30 regarding the `clock` error. If you have time, could you see if that fixes the issue?

If the assertion still fails, we'll have to look a bit more closer to understand why it was supposed to be 4, and if the issue is the 4 or the 3 that we are now getting.

**Comment by Tom-python0121** [comment]
@DePierre ,at present，I was using a beta version instead of a release version and one of the issues has been resolved and expected a new version to be released，but the assertion still fails when I test ,and the **effects_count** is the 3 that we are now getting,but In the source code, **effects_count** is 4, causing the AssertionError problem. I hope my test can help you.
```console
[root@centos8 CANToolz]# python setup.py test
……
0x111:3:001122
0x6f:4:00112233
0x111:5:0011223344
hw_USBtin: CMD: C try: 2
ok
test_bind (tests.stream.test_forced_sampler.TestForcedSampler) ... ok
test_process (tests.stream.test_forced_sampler.TestForcedSampler) ... FAIL

======================================================================
FAIL: test_process (tests.stream.test_forced_sampler.TestForcedSampler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/CANToolz/tests/stream/test_forced_sampler.py", line 33, in test_process
    self.assertEqual(effects_count, 4)
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 28 tests in 156.778s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=28 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=28 errors=0 failures=1>
```

**Comment by Tom-python0121** [comment]
If my problem has been resolved, please let me know? The problem still exists in this version.
